/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { MigrationsContract } from "./Migrations";
import { SimpleStorageContract } from "./SimpleStorage";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Migrations"): MigrationsContract;
      require(name: "SimpleStorage"): SimpleStorageContract;
    }
  }
}

export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { SimpleStorageContract, SimpleStorageInstance } from "./SimpleStorage";
